<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="/Users/mike.mclafferty/Repos/jestbug/__tests__/component.test.ts" errors="0" package="/Users/mike.mclafferty/Repos/jestbug/__tests__/component.test.ts" hostname="localhost" tests="3" failures="1" time="139.079" timestamp="2018-03-06T18:16:47">
    <properties>
    </properties>
    <testcase classname="Component Tests" name="should return 0" time="0">
    </testcase>
    <testcase classname="Component Tests" name="should return 5" time="0">
    </testcase>
    <testcase classname="Component Tests" name="should fail" time="0">
      <failure message="TypeError: console.error.blah is not a function
    at Component.Object.&lt;anonymous&gt;.Component.executeSomeLogic (/Users/mike.mclafferty/Repos/jestbug/component.ts:22:28)
    at Object.&lt;anonymous&gt; (/Users/mike.mclafferty/Repos/jestbug/__tests__/component.test.ts:25:30)
    at Object.asyncFn (/Users/mike.mclafferty/Repos/jestbug/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/Users/mike.mclafferty/Repos/jestbug/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/mike.mclafferty/Repos/jestbug/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/Users/mike.mclafferty/Repos/jestbug/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>